### ISSUE TITLE
feat: Header

### ISSUE THREAD

**Issue by laurenCho9** [supercoding-final-project/supercoding-final-project-front#11]
## 💡 목적

헤더 ui 및 포함된 기능 전부 구현

## 📝 Todo
<img width="1913" alt="image" src="https://github.com/supercoding-final-project/supercoding-final-project-front/assets/117485593/a46740da-d830-464b-9914-1bfb78adf5df">

- [ ] ui 구현
- [ ] position fixed 적용하기
- [ ] 스크롤 이벤트 기능 구현하기
- [ ] 검색 시 리스트페이지로 이동

## ‼️ 주의 사항

- 너비값 100% 안에 지정 너비 1024px 로 감싸서 중앙정렬하기.
- 멘토 헤더 별도 작업 필요
